# Generated by Django 6.0.1 on 2026-02-01 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('issue_type', models.CharField(max_length=50)),
                ('location_type', models.CharField(max_length=50)),
                ('issue_location', models.CharField(max_length=255)),
                ('end_user', models.CharField(blank=True, max_length=255)),
                ('recorded_by', models.CharField(blank=True, max_length=255)),
                ('assigned_vendor', models.CharField(blank=True, max_length=255)),
                ('assigned_engineers', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_history', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
