# Generated by Django 6.0.1 on 2026-02-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_issuelocationtype_issuetype_statustype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuelocationtype',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
