# Generated by Django 6.0.1 on 2026-02-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_issuelocationtype_desc_alter_issuetype_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuelocationtype',
            name='cd',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='cd',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='cd',
            field=models.CharField(max_length=20),
        ),
    ]
