# Generated by Django 6.0.1 on 2026-02-02 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_issuelocationtype_cd_alter_issuetype_cd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.issuetype'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.issuelocationtype'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.statustype'),
        ),
    ]
