# Generated by Django 6.0.1 on 2026-02-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_issue_type_alter_ticket_location_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuelocationtype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='issuetype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='statustype',
            name='id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='issuelocationtype',
            name='cd',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='cd',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='cd',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_engineers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
