# Generated by Django 6.0.1 on 2026-02-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketuseraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketuseraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
