# Generated by Django 6.0.1 on 2026-02-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketuser', '0002_ticketuseraddress_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='ticketuser',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
